### ISSUE TITLE
Invalid open-api output for remote agent

### ISSUE THREAD

**Issue by cre8** [uport-project/veramo#1235]
**Bug severity**
4

**Describe the bug**
The output from the remove serve page under `/open-api.json` is not compliant so it's impossible to generate SDKs out of it

**To Reproduce**
Steps to reproduce the behaviour:
Use the example code from https://veramo.io/docs/api/remote-server
It will output something like:

[open-api.txt](https://github.com/uport-project/veramo/files/12474898/open-api.txt)

 
Go to https://apitools.dev/swagger-parser/online/ and validate it

Even when turning of all validation features, one error still remains:
```
Circular $ref pointer found at https://apitools.dev/swagger-parser/online/#/components/schemas/VerificationMethod/properties/conditionOr/items

Error: Circular $ref pointer found at https://apitools.dev/swagger-parser/online/#/components/schemas/VerificationMethod/properties/conditionOr/items
    at o (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:95564)
    at https://apitools.dev/swagger-parser/online/js/bundle.min.js:29:45042

ReferenceError: Circular $ref pointer found at https://apitools.dev/swagger-parser/online/#/components/schemas/VerificationMethod/properties/conditionOr/items
    at Function.o [as reference] (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:95564)
    at foundCircularReference (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:14971)
    at dereference$Ref (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:14667)
    at crawl (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:14259)
    at crawl (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:14354)
    at crawl (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:14354)
    at dereference$Ref (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:14744)
    at crawl (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:14259)
    at crawl (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:14354)
    at crawl (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:14354)
```

**Observed behaviour**
The output is not compliant so it can not be used. I haven't tested it with the veramo client since I am unable to use it in my commonjs application.
   
**Expected behaviour**
To be compliant

**Versions (please complete the following information):**
 - Veramo: 5.4.1
 - Node Version 18

**Comment by mirceanis** [comment]
Some small progress on this issue..

We rely on automation to generate the OpenAPI. It uses Typescript types and inline documentation to generate the OpenAPI spec.

* Using https://editor.swagger.io is a bit more helpful in pinpointing problematic lines in the `/open-api.json` output. It is also able to generate the SDKs. Please let me know if this works for you too.
* It seems some typescript constructs don't translate well to OpenAPI
Examples:
  * `@context` is an array of `string`, but the first element is a hardcoded `const string` according to the VC or DID specs. The const is not interpreted correctly here.
  * same for the `type` property of VCs
  * some other polymorphic nested types also fail
