### ISSUE TITLE
Agent - API Error in /createVerifiableCredential endpoint

### ISSUE THREAD

**Issue by pvanroos** [uport-project/veramo#327]
**Bug severity**
4

**Describe the bug**
I am attempting to POST a VerifiableCredential to the following endpoint: 

/createVerifiableCredential

Other endpoints work but I get a 500 when submitting the following JSON payload:

{
  "@context": [
    "https://www.w3.org/2018/credentials/v1"
  ],
  "type": ["VerifiableCredential"],
  "issuer": {"id": "did:web:veramo-agent-prime-1.herokuapp.com"},
  "issuanceDate": "2020-12-27T10:15:00Z",
  "credentialSubject": {
    "id": "did:ethr:rinkeby:0x6156c1cdab8914525a3eb2b148e82380a5c12e51",
    "community": {
        "rank": "Captain",
        "RankExpiration": "2021-12-27T10:15:00Z"
    }
  },
  "proof": {
    "type": "RsaSignature2018",
    "created": "2020-12-27T10:15:00Z",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "https://test.io/issuers/keys/1",
    "jws": "MyDigitalSignature"
  }
}

**To Reproduce**
1. Open postman and set the POST for the following url path:  /agent/createVerifiableCredential
2. Make sure your Bearer token is set
3. Set Raw JSON content-type
4. Add JSON payload above

**Observed behavior**
500 - Response JSON: 
{
    "error": "Cannot read property '@context' of undefined"
}
   
**Expected behaviour**
201 (200) - VerifiableCredential created

**Details**
n/a

**Additional context**
Running Agent on Heroku

**Versions (please complete the following information):**
 - Veramo: First version released on 12/24/2020
 - Postman:  v7.36.1
 - See wellknown: https://veramo-agent-prime-1.herokuapp.com/.well-known/did.json

**Comment by jasonhealy** [comment]
What happens when you create a VC using the swagger docs? http://veramo-agent-prime-1.herokuapp.com/api-docs/#/default/createVerifiableCredential

Also can you double check payloads against integration tests?: https://github.com/uport-project/veramo/blob/next/__tests__/shared/verifiableData.ts

**Comment by simonas-notcat** [comment]
https://veramo.io/docs/api/credential-w3c.icreateverifiablecredentialargs

**Comment by simonas-notcat** [comment]
Schema validation is off by default:

https://github.com/uport-project/veramo/blob/next/packages/cli/default/default.yml#L99

`"error": "Cannot read property '@context' of undefined"` is not that informative

@mirceanis

**Comment by pvanroos** [comment]
I should have looked harder for the tests folder. Sorry. 

Anyway, I modified the JSON payload to match the 'simple' test shown in the test file:  https://github.com/uport-project/veramo/blob/next/__tests__/shared/verifiableData.ts

{
  "issuer": {"id": "did:web:veramo-agent-prime-1.herokuapp.com"},
  "credentialSubject": {
    "id": "did:ethr:rinkeby:0x6156c1cdab8914525a3eb2b148e82380a5c12e51",
    "you": "rock"    
  },
  "proofFormat":"jwt"
}

Same error is returning in response. If it works directly via JS/TS, then it might be a bug in the API code (especially if the TS tests are all passing)?

**Comment by simonas-notcat** [comment]
@pvanroos can you turn on debug mode in heroku:

- `Heroku app dashboard > Settings > Reveal Config Vars`
- Add key `DEBUG`, value `veramo:*`
- Call the API with the same payload 
- `Heroku app dashboard > More > View logs`

Can you paste the line that has `veramo:agent:createVerifiableCredential` ?

**Comment by pvanroos** [comment]
2020-12-28T22:48:27.176706+00:00 app[web.1]: 2020-12-28T22:48:27.176Z veramo:agent:createVerifiableCredential { '@context': [ 'https://www.w3.org/2018/credentials/v1', 'https://example.com/1/2/3' ], type: [ 'VerifiableCredential' ], issuer: { id: 'did:web:veramo-agent-prime-1.herokuapp.com' }, issuanceDate: '2020-12-27T10:15:00Z', credentialSubject: { id: 'did:ethr:rinkeby:0x6156c1cdab8914525a3eb2b148e82380a5c12e51', community: { rank: 'Captain', RankExpiration: '2021-12-27T10:15:00Z' } }, proof: { type: 'RsaSignature2018', created: '2020-12-27T10:15:00Z', proofPurpose: 'assertionMethod', verificationMethod: 'https://test.io/issuers/keys/1', jws: 'MyDigitalSignature' } }
2020-12-28T22:48:27.179664+00:00 app[web.1]: 2020-12-28T22:48:27.179Z veramo:w3c:action-handler TypeError: Cannot read property '@context' of undefined
2020-12-28T22:48:27.179665+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/@veramo/credential-w3c/build/action-handler.js:68:115)
2020-12-28T22:48:27.179666+00:00 app[web.1]:     at Generator.next (<anonymous>)
2020-12-28T22:48:27.179667+00:00 app[web.1]:     at /app/node_modules/@veramo/credential-w3c/build/action-handler.js:8:71
2020-12-28T22:48:27.179667+00:00 app[web.1]:     at new Promise (<anonymous>)
2020-12-28T22:48:27.179668+00:00 app[web.1]:     at __awaiter (/app/node_modules/@veramo/credential-w3c/build/action-handler.js:4:12)
2020-12-28T22:48:27.179687+00:00 app[web.1]:     at Object.createVerifiableCredential (/app/node_modules/@veramo/credential-w3c/build/action-handler.js:66:16)
2020-12-28T22:48:27.179688+00:00 app[web.1]:     at Agent.<anonymous> (/app/node_modules/@veramo/core/build/agent.js:159:54)
2020-12-28T22:48:27.179688+00:00 app[web.1]:     at Generator.next (<anonymous>)
2020-12-28T22:48:27.179689+00:00 app[web.1]:     at /app/node_modules/@veramo/core/build/agent.js:8:71
2020-12-28T22:48:27.179689+00:00 app[web.1]:     at new Promise (<anonymous>)

**Comment by simonas-notcat** [comment]
You said that you have modified the payload to look like this:


```javascript
{
  "issuer": {"id": "did:web:veramo-agent-prime-1.herokuapp.com"},
  "credentialSubject": {
    "id": "did:ethr:rinkeby:0x6156c1cdab8914525a3eb2b148e82380a5c12e51",
    "you": "rock"    
  },
  "proofFormat":"jwt"
}
```

But actually, you can see in your logs, that your payload is:

```javascript
{
  '@context': ['https://www.w3.org/2018/credentials/v1', 'https://example.com/1/2/3'],
  type: ['VerifiableCredential'],
  issuer: {
    id: 'did:web:veramo-agent-prime-1.herokuapp.com'
  },
  issuanceDate: '2020-12-27T10:15:00Z',
  credentialSubject: {
    id: 'did:ethr:rinkeby:0x6156c1cdab8914525a3eb2b148e82380a5c12e51',
    community: {
      rank: 'Captain',
      RankExpiration: '2021-12-27T10:15:00Z'
    }
  },
  proof: {
    type: 'RsaSignature2018',
    created: '2020-12-27T10:15:00Z',
    proofPurpose: 'assertionMethod',
    verificationMethod: 'https://test.io/issuers/keys/1',
    jws: 'MyDigitalSignature'
  }
}
```

**Comment by simonas-notcat** [comment]
@pvanroos  the payload should be

```javascript
{
  "credential": {
    "issuer": {
      "id": "did:web:veramo-agent-prime-1.herokuapp.com"
    },
    "credentialSubject": {
      "id": "did:ethr:rinkeby:0x6156c1cdab8914525a3eb2b148e82380a5c12e51",
      "you": "rock"    
    }
  },
  "proofFormat": "jwt",
  "save": true
}    
```

The same as in our [integration tests](https://github.com/uport-project/veramo/blob/next/__tests__/shared/verifiableData.ts#L57)

**Comment by pvanroos** [comment]
You're right--it worked.  Sorry. Too much beer and wine over the holidays.  ;-) 

The ts tests really help. I will use them as a guide from now on.  Thanks @simonas-notcat
