### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by bishalkc** [uport-project/veramo#513]
Getting the follow error with `yarn build` 

```
#10 140.8 lerna ERR! yarn run generate-plugin-schema stderr:
#10 140.8 Warning: src/action-handler.ts:50:7 - (tsdoc-at-sign-in-word) The "@" character looks like part of a TSDoc tag; use a backslash to escape it
#10 140.8 Warning: src/action-handler.ts:97:7 - (tsdoc-at-sign-in-word) The "@" character looks like part of a TSDoc tag; use a backslash to escape it
#10 140.8 Warning: src/index.ts:18:7 - (ae-missing-release-tag) "schema" is exported by the package, but it is missing a release tag (@alpha, @beta, @public, or @internal)
#10 140.8 /usr/src/app/packages/cli/build/dev.js:50
#10 140.8         schema.definitions['W3CCredential']['properties']['credentialSubject']['additionalProperties'] = true;
#10 140.8                                            ^
#10 140.8
#10 140.8 TypeError: Cannot read property 'properties' of undefined
#10 140.8     at createSchema (/usr/src/app/packages/cli/build/dev.js:50:44)
#10 140.8     at /usr/src/app/packages/cli/build/dev.js:141:99
#10 140.8     at Generator.next (<anonymous>)
#10 140.8     at /usr/src/app/packages/cli/build/dev.js:27:71
#10 140.8     at new Promise (<anonymous>)
#10 140.8     at __awaiter (/usr/src/app/packages/cli/build/dev.js:23:12)
#10 140.8     at Command.<anonymous> (/usr/src/app/packages/cli/build/dev.js:95:26)
#10 140.8     at Command.listener [as _actionHandler] (/usr/src/app/packages/cli/node_modules/commander/index.js:907:31)
#10 140.8     at Command._parseCommand (/usr/src/app/packages/cli/node_modules/commander/index.js:1491:14)
#10 140.8     at Command._dispatchSubcommand (/usr/src/app/packages/cli/node_modules/commander/index.js:1436:18)
#10 140.8 error Command failed with exit code 1.
#10 140.8 error Command failed with exit code 1.
#10 140.8 lerna ERR! yarn run generate-plugin-schema exited 1 in '@veramo/credential-w3c'
#10 140.8 lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
#10 140.8 error Command failed with exit code 1.
#10 140.8 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#10 140.8 error Command failed with exit code 1.
#10 140.8 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c yarn build]: exit code: 1
```

**Comment by jasonhealy** [comment]
Thanks for reporting - 

Can you provide some more context to the issue? Node Version, OS, Veramo Version etc

**Comment by bishalkc** [comment]
Node Version - v16.1.0
Veramo Version - 1.2.1 (next)
OS - Mac OS Big Sur 11.3

**Comment by jasonhealy** [comment]
@bishalkc I am able to recreate the issue on Node v16.1.0. There appears to be some dependency incompatibilities that we would need to look into. Can you try using v14.17.0 LTS ? 

Note: You will need to clear your yarn cache and delete the node modules folder before installing/building with new node version.

**Comment by bishalkc** [comment]
@jasonhealy no issue with node 14. 

Thanks
