### ISSUE TITLE
Error adding service endpoint to DID document

### ISSUE THREAD

**Issue by jasonhealy** [uport-project/veramo#522]
**Bug severity**
3

**Describe the bug**

Error updating did document using `veramo did add-service`

`Error: invalid signer or provider (argument="signerOrProvider", value={"options":{},"timeout":0,"provider":{"host":"https://rinkeby.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c","timeout":0},"rpc":{"options":{"jsonSpace":0,"max":9999999999999},"idCounter":3801765146639,"currentProvider":{"host":"https://rinkeby.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c","timeout":0}}}, code=INVALID_ARGUMENT, version=contracts/5.1.1)
    at Logger.makeError (~/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@ethersproject/logger/lib/index.js:180:21)
    at Logger.throwError (~/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@ethersproject/logger/lib/index.js:189:20)
    at Logger.throwArgumentError (~/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@ethersproject/logger/lib/index.js:192:21)
    at Contract.BaseContract (~/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@ethersproject/contracts/lib/index.js:598:20)
    at new Contract (~/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@ethersproject/contracts/lib/index.js:1017:42)
    at Contract.BaseContract.connect (~/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@ethersproject/contracts/lib/index.js:786:24)
    at P (~/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/ethr-did-resolver/lib/index.umd.js:1:3285)
    at new K (~/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/ethr-did-resolver/lib/index.umd.js:1:3985)
    at new o (~/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/ethr-did/lib/index.js:1:1618)
    at EthrDIDProvider.<anonymous> (~/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@veramo/did-provider-ethr/build/ethr-did-provider.js:106:29) {
  reason: 'invalid signer or provider',
  code: 'INVALID_ARGUMENT',
  argument: 'signerOrProvider',
  value: SignerProvider {
    options: {
      provider: [Function: HttpProvider],
      signTransaction: [Function: signTransaction]
    },
    timeout: 0,
    provider: HttpProvider {
      host: 'https://rinkeby.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c',
      timeout: 0
    },
    rpc: EthRPC {
      options: [Object],
      idCounter: 3801765146639,
      setProvider: [Function (anonymous)],
      currentProvider: [HttpProvider]
    }
  }
}`

**Versions (please complete the following information):**
 - Veramo: [1.2]
 - Browser [NA]
 - Node Version [14]

**Comment by jasonhealy** [comment]
Originally reported in discussion forum https://github.com/uport-project/veramo/discussions/508
