### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Brummos** [uport-project/veramo#639]
Following the readme, the command yarn build results in the following error.

TypeError: Cannot read property 'pluginInterfaces' of undefined
    at C:\Git\Veramo\veramo\packages\cli\build\dev.js:105:60
    at Generator.next (<anonymous>)
    at C:\Git\Veramo\veramo\packages\cli\build\dev.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Git\Veramo\veramo\packages\cli\build\dev.js:23:12)
    at Command.<anonymous> (C:\Git\Veramo\veramo\packages\cli\build\dev.js:90:26)
    at Command.listener [as _actionHandler] (C:\Git\Veramo\veramo\packages\cli\node_modules\commander\index.js:922:31)
    at Command._parseCommand (C:\Git\Veramo\veramo\packages\cli\node_modules\commander\index.js:1503:14)
    at Command._dispatchSubcommand (C:\Git\Veramo\veramo\packages\cli\node_modules\commander\index.js:1443:18)
    at Command._parseCommand (C:\Git\Veramo\veramo\packages\cli\node_modules\commander\index.js:1460:12)

Anything i can do to fix this?

**Comment by mirceanis** [comment]
Hi, is this the only output or is there more?
Please share as many details as possible.
