### ISSUE TITLE
Veramo CLI fails to add key and raises exception

### ISSUE THREAD

**Issue by bafu** [uport-project/veramo#641]
**Bug severity**
4

**Describe the bug**
Veramo CLI fails to add key and raises exception "untyped transactions do not support accessList".

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a testing DID for Rinkeby.
2. Deposit 0.1 ETH to the address in `blockchainAccountId`.
3. Run the command `veramo did add-key`

**Observed behaviour**
Veramo CLI fails to add key and raises exception "untyped transactions do not support accessList".
   
**Expected behaviour**
Veramo CLI creates a transaction on Rinkeby.

**Details**
Exception log

```
$ veramo did add-key
? Select DID did:ethr:rinkeby:0x037d8d76ef014fc4015c5ba7d466b9ca0e23f9de5f1d731bff8ca1e0ffdc68f635
? Select key management system local
? Type Secp256k1
Error: untyped transactions do not support accessList; include type: 1 (argument="transaction", value={"chainId":4,"nonce":0,"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x3b9aca00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x3b9aca00"},"gasPrice":null,"gasLimit":{"type":"BigNumber","hex":"0x0f4241"},"to":"0xdCa7EF03e98e0DC2B855bE647C39ABe984fcF21B","value":{"type":"BigNumber","hex":"0x00"},"data":"0x7ad4b0a400000000000000000000000063a01d100072d951a9cde0cbff4eb80caca867666469642f7075622f536563703235366b312f766572694b65792f68657800000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000001da9c01000000000000000000000000000000000000000000000000000000000000004104af341d6ecdfb2ba226a0dc0bcb1af8024d563bacb7b565eee5449924010b4dedec239ae4e26600826faa47a22583f5b14d6545a0b10f4807210649d13ff254f000000000000000000000000000000000000000000000000000000000000000","accessList":[]}, code=INVALID_ARGUMENT, version=transactions/5.4.0)
    at Logger.makeError (/home/bafu/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@ethersproject/logger/lib/index.js:187:21)
    at Logger.throwError (/home/bafu/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@ethersproject/logger/lib/index.js:196:20)
    at Logger.throwArgumentError (/home/bafu/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@ethersproject/logger/lib/index.js:199:21)
    at Object.serialize (/home/bafu/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@ethersproject/transactions/lib/index.js:243:20)
    at /home/bafu/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@ethersproject/wallet/lib/index.js:166:97 {
  reason: 'untyped transactions do not support accessList; include type: 1',
  code: 'INVALID_ARGUMENT',
  argument: 'transaction',
  value: {
    chainId: 4,
    nonce: 0,
    maxPriorityFeePerGas: BigNumber { _hex: '0x3b9aca00', _isBigNumber: true },
    maxFeePerGas: BigNumber { _hex: '0x3b9aca00', _isBigNumber: true },
    gasPrice: null,
    gasLimit: BigNumber { _hex: '0x0f4241', _isBigNumber: true },
    to: '0xdCa7EF03e98e0DC2B855bE647C39ABe984fcF21B',
    value: BigNumber { _hex: '0x00', _isBigNumber: true },
    data: '0x7ad4b0a400000000000000000000000063a01d100072d951a9cde0cbff4eb80caca867666469642f7075622f536563703235366b312f766572694b65792f68657800000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000001da9c01000000000000000000000000000000000000000000000000000000000000004104af341d6ecdfb2ba226a0dc0bcb1af8024d563bacb7b565eee5449924010b4dedec239ae4e26600826faa47a22583f5b14d6545a0b10f4807210649d13ff254f000000000000000000000000000000000000000000000000000000000000000',
    accessList: []
  }
}
```

Testing DID details

```
$ veramo did list
┌──────────────────┬───────────┬───────────────────────────────────────────────────────────────────────────────────────┐
│         provider │     alias │                                                                                   did │
├──────────────────┼───────────┼───────────────────────────────────────────────────────────────────────────────────────┤
│ did:ethr:rinkeby │           │ did:ethr:rinkeby:0x031e9a307fca6ff0c01854d7cd592354a667f3522a5aec2a93519226b16615121b │
│ did:ethr:rinkeby │       Yui │ did:ethr:rinkeby:0x037d8d76ef014fc4015c5ba7d466b9ca0e23f9de5f1d731bff8ca1e0ffdc68f635 │
│          did:web │ localhost │                                                                     did:web:localhost │
└──────────────────┴───────────┴───────────────────────────────────────────────────────────────────────────────────────┘

$ veramo did resolve did:ethr:rinkeby:0x037d8d76ef014fc4015c5ba7d466b9ca0e23f9de5f1d731bff8ca1e0ffdc68f635
{
  "didDocumentMetadata": {},
  "didResolutionMetadata": {
    "contentType": "application/did+ld+json"
  },
  "didDocument": {
    "@context": [
      "https://www.w3.org/ns/did/v1",
      "https://identity.foundation/EcdsaSecp256k1RecoverySignature2020/lds-ecdsa-secp256k1-recovery2020-0.0.jsonld"
    ],
    "id": "did:ethr:rinkeby:0x037d8d76ef014fc4015c5ba7d466b9ca0e23f9de5f1d731bff8ca1e0ffdc68f635",
    "verificationMethod": [
      {
        "id": "did:ethr:rinkeby:0x037d8d76ef014fc4015c5ba7d466b9ca0e23f9de5f1d731bff8ca1e0ffdc68f635#controller",
        "type": "EcdsaSecp256k1RecoveryMethod2020",
        "controller": "did:ethr:rinkeby:0x037d8d76ef014fc4015c5ba7d466b9ca0e23f9de5f1d731bff8ca1e0ffdc68f635",
        "blockchainAccountId": "0x63A01D100072D951A9CDE0cBff4EB80CACA86766@eip155:4"
      },
      {
        "id": "did:ethr:rinkeby:0x037d8d76ef014fc4015c5ba7d466b9ca0e23f9de5f1d731bff8ca1e0ffdc68f635#controllerKey",
        "type": "EcdsaSecp256k1VerificationKey2019",
        "controller": "did:ethr:rinkeby:0x037d8d76ef014fc4015c5ba7d466b9ca0e23f9de5f1d731bff8ca1e0ffdc68f635",
        "publicKeyHex": "0x037d8d76ef014fc4015c5ba7d466b9ca0e23f9de5f1d731bff8ca1e0ffdc68f635"
      }
    ],
    "authentication": [
      "did:ethr:rinkeby:0x037d8d76ef014fc4015c5ba7d466b9ca0e23f9de5f1d731bff8ca1e0ffdc68f635#controller",
      "did:ethr:rinkeby:0x037d8d76ef014fc4015c5ba7d466b9ca0e23f9de5f1d731bff8ca1e0ffdc68f635#controllerKey"
    ],
    "assertionMethod": [
      "did:ethr:rinkeby:0x037d8d76ef014fc4015c5ba7d466b9ca0e23f9de5f1d731bff8ca1e0ffdc68f635#controller",
      "did:ethr:rinkeby:0x037d8d76ef014fc4015c5ba7d466b9ca0e23f9de5f1d731bff8ca1e0ffdc68f635#controllerKey"
    ]
  }
}
```

**Additional context**
N/A

**Versions (please complete the following information):**
 - Veramo: 2.0.1

**Comment by bafu** [comment]
I got a different error after updated to v2.1.1

```
$ veramo did add-key 
? Select DID did:ethr:rinkeby:0x037d8d76ef014fc4015c5ba7d466b9ca0e23f9de5f1d731b
ff8ca1e0ffdc68f635
? Select key management system local
? Type Secp256k1
Error: untyped transactions do not support accessList; include type: 1 (argument="transaction", value={"chainId":4,"nonce":0,"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x3b9aca00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x3b9aca00"},"gasPrice":null,"gasLimit":{"type":"BigNumber","hex":"0x0f4241"},"to":"0xdCa7EF03e98e0DC2B855bE647C39ABe984fcF21B","value":{"type":"BigNumber","hex":"0x00"},"data":"0x7ad4b0a400000000000000000000000063a01d100072d951a9cde0cbff4eb80caca867666469642f7075622f536563703235366b312f766572694b65792f68657800000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000001da9c010000000000000000000000000000000000000000000000000000000000000041045897736868314b4d6cdaa980052a2422a25b12f83be9593aa23c62221179dea8e7aa849a8f2a7429bc9af1909f468fe62cea96e89bd542bcd5a8955bf6ebe0c700000000000000000000000000000000000000000000000000000000000000","accessList":[]}, code=INVALID_ARGUMENT, version=transactions/5.4.0)
    at Logger.makeError (/home/bafu/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@ethersproject/logger/lib/index.js:187:21)
    at Logger.throwError (/home/bafu/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@ethersproject/logger/lib/index.js:196:20)
    at Logger.throwArgumentError (/home/bafu/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@ethersproject/logger/lib/index.js:199:21)
    at Object.serialize (/home/bafu/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@ethersproject/transactions/lib/index.js:243:20)
    at /home/bafu/.nvm/versions/node/v14.16.1/lib/node_modules/@veramo/cli/node_modules/@ethersproject/wallet/lib/index.js:166:97 {
  reason: 'untyped transactions do not support accessList; include type: 1',
  code: 'INVALID_ARGUMENT',
  argument: 'transaction',
  value: {
    chainId: 4,
    nonce: 0,
    maxPriorityFeePerGas: BigNumber { _hex: '0x3b9aca00', _isBigNumber: true },
    maxFeePerGas: BigNumber { _hex: '0x3b9aca00', _isBigNumber: true },
    gasPrice: null,
    gasLimit: BigNumber { _hex: '0x0f4241', _isBigNumber: true },
    to: '0xdCa7EF03e98e0DC2B855bE647C39ABe984fcF21B',
    value: BigNumber { _hex: '0x00', _isBigNumber: true },
    data: '0x7ad4b0a400000000000000000000000063a01d100072d951a9cde0cbff4eb80caca867666469642f7075622f536563703235366b312f766572694b65792f68657800000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000001da9c010000000000000000000000000000000000000000000000000000000000000041045897736868314b4d6cdaa980052a2422a25b12f83be9593aa23c62221179dea8e7aa849a8f2a7429bc9af1909f468fe62cea96e89bd542bcd5a8955bf6ebe0c700000000000000000000000000000000000000000000000000000000000000',
    accessList: []
  }
}
```

I am happy to share more logs or do some tests if you can share the testing steps with me. Thanks!
