### ISSUE TITLE
Missing uuid dependency in @veramo/key-manager

### ISSUE THREAD

**Issue by ferrerogg** [uport-project/veramo#853]
**Bug severity**
3

**Describe the bug**
*@veramo/key-manager* dependency does not explicitly list *uuid* as a dependency.
As of *sqlite 5.0.2*, this dependency is automatically resolved as a "side effect", but with newer *sqlite 5.0.3* this is no longer the case

**To Reproduce**
Steps to reproduce the behaviour:
1. follow tutorial at [https://veramo.io/docs/node_tutorials/node_setup_identifiers](https://veramo.io/docs/node_tutorials/node_setup_identifiers)
2. run the command `npm run id:list`

**Observed behaviour**
The following error is thrown:
```
Error: Cannot find module 'uuid'
Require stack:
- /home/janny/projects/blockchain/SSI/VERAMO/veramo-agent_test/node_modules/@veramo/key-manager/build/memory-key-store.js
- /home/janny/projects/blockchain/SSI/VERAMO/veramo-agent_test/node_modules/@veramo/key-manager/build/index.js
- /home/janny/projects/blockchain/SSI/VERAMO/veramo-agent_test/src/veramo/setup.ts
- /home/janny/projects/blockchain/SSI/VERAMO/veramo-agent_test/src/list-identifiers.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/home/janny/projects/blockchain/SSI/VERAMO/veramo-agent_test/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/janny/projects/blockchain/SSI/VERAMO/veramo-agent_test/node_modules/@veramo/key-manager/src/memory-key-store.ts:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/janny/projects/blockchain/SSI/VERAMO/veramo-agent_test/node_modules/@veramo/key-manager/build/memory-key-store.js',
    '/home/janny/projects/blockchain/SSI/VERAMO/veramo-agent_test/node_modules/@veramo/key-manager/build/index.js',
    '/home/janny/projects/blockchain/SSI/VERAMO/veramo-agent_test/src/veramo/setup.ts',
    '/home/janny/projects/blockchain/SSI/VERAMO/veramo-agent_test/src/list-identifiers.ts'
  ]
}
```
   
**Expected behaviour**
The test should run fine with sqlite 5.0.2, but not with sqlite 5.0.3

**Temporary fix**
Add uuid as a dependency with `yarn add uuid`

**Comment by mirceanis** [comment]
Thanks for reporting this, and kudos for an excellent bug report!

Are you also willing to post a PR with the fix?

**Comment by ferrerogg** [comment]
Just noticed that the fix is already present in @next branch

[fix: add missing uuid dependency](https://github.com/uport-project/veramo/pull/807)
